dist: bionic
language: python

python:
 - "3.6"
 - "3.7"
 - "3.8-dev"

before_install:
  - sudo apt-get install -y texlive-xetex fonts-lmodern

install:
 - pip install matplotlib>=1.2 coverage pytest-cov codecov

script:
 - pytest

after_success:
 - codecov
