[tool.isort]
profile = "black"
atomic = true
combine_as_imports = true
force_sort_within_sections = true
lines_after_imports = 2

[tool.pytest.ini_options]
addopts = "-v --cov=pgfutils --cov-report html --cov-report term --cov-branch"
filterwarnings = [
    "ignore:The distutils package is deprecated",
    "ignore:numpy.ndarray size changed"
]
