# SPDX-FileCopyrightText: Blair Bonnett
# SPDX-License-Identifier: 0BSD

[project]
site_name = "matplotlib-pgfutils"
docs_dir = "doc"
site_dir = "build/doc"
repo_url = "https://github.com/bcbnz/matplotlib-pgfutils"

nav = [
  {"Introduction" = "index.md"},
  "usage.md",
  "config.md",
  "interactive.md",
  "file_tracking.md",
  "latexmk.md",
  "advanced.md",
]

[project.theme]
features = [
  "content.code.copy"
]

[project.theme.icon]
repo = "fontawesome/brands/github"

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true

[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.superfences]
