# SPDX-FileCopyrightText: Blair Bonnett
# SPDX-License-Identifier: BSD-3-Clause

name: Check code formatting
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run-linters:
    runs-on: ubuntu-latest

    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        id: setup
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          architecture: x64

      - name: Download ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: version

      - name: Lint
        run: ruff check

      - name: Check formatting
        run: ruff format --check
